force-app/main/default/objects/myHirer__c/myHirer__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>myHirer</label>
</CustomObject>

force-app/main/default/objects/mymeta__mdt/mymeta__mdt.object-meta.xml
<CustomObject>
    <label>mymeta</label>
    <pluralLabel>mymetas</pluralLabel>
</CustomObject>

force-app/main/default/objects/mymeta__mdt/fields/is_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/mysettings__c/mysettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>my settings</label>
</CustomObject>

force-app/main/default/classes/customSettingsDemo.cls
public class customSettingsDemo {
    
    public void mymeth(){
       // mysettings__c mcs = mysettings__c.getInstance('mytrigger');
       //myHirer__c mh =  myHirer__c.getInstance('005dL0000006PN7');
       mymeta__mdt md = mymeta__mdt.getInstance('trionoff');
        if(md.is_Active__c){
            system.debug('Call the trigger');
        }else{
            system.debug('dont call the trigger');
        }
        
    }

}